-- Database Cleanup Script
-- Generated by Antigravity Agent
-- Purpose: Drop tables identified as irrelevant to the current schema in 'backend/supabase/schema.sql'

BEGIN;

DROP TABLE IF EXISTS "payment_preferences" CASCADE;
DROP TABLE IF EXISTS "cache" CASCADE;
DROP TABLE IF EXISTS "prompts" CASCADE;
DROP TABLE IF EXISTS "human_handoffs" CASCADE;
DROP TABLE IF EXISTS "admins" CASCADE;
DROP TABLE IF EXISTS "session_events" CASCADE;
DROP TABLE IF EXISTS "content" CASCADE;
DROP TABLE IF EXISTS "transcripts" CASCADE;
DROP TABLE IF EXISTS "session_stages" CASCADE;
DROP TABLE IF EXISTS "documents" CASCADE;
DROP TABLE IF EXISTS "stage_completions" CASCADE;
DROP TABLE IF EXISTS "utterances" CASCADE;
DROP TABLE IF EXISTS "stages" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "system_config" CASCADE;

COMMIT;

-- Verify required tables still exist
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';
