
export const validationService = {
    /**
     * Validates the AI response against stage-specific rules.
     * @param {string} text - The text generated by the AI.
     * @param {object} stageConfig - The configuration for the current stage.
     * @returns {boolean} - True if valid, false otherwise.
     */
    validateResponse(text, stageConfig) {
        if (!text) return false;
        if (!stageConfig || !stageConfig.validation_rules) return true; // No rules, pass by default

        const rules = stageConfig.validation_rules;

        // 1. Min Length Check
        if (rules.min_length && text.length < rules.min_length) {
            console.warn(`Validation Failed: Response too short (${text.length} < ${rules.min_length})`);
            return false;
        }

        // 2. Forbidden Words Check
        if (rules.forbidden_words && Array.isArray(rules.forbidden_words)) {
            const lowerText = text.toLowerCase();
            for (const word of rules.forbidden_words) {
                if (lowerText.includes(word.toLowerCase())) {
                    console.warn(`Validation Failed: Contains forbidden word '${word}'`);
                    return false;
                }
            }
        }

        return true;
    },

    /**
     * Validates if the stage completion criteria are met based on the summary.
     * @param {string} summary - The summary provided by the AI for stage completion.
     * @param {object} stageConfig - The configuration for the current stage.
     * @returns {boolean} - True if valid found, false otherwise.
     */
    validateStageCompletion(summary, stageConfig) {
        if (!summary) return false;
        // In a real scenario, this might involve another AI call to grade the summary 
        // or checking for specific keywords. For now, we enforce a reasonable length 
        // to ensure the AI isn't hallucinating a completion with empty content.

        if (summary.length < 20) {
            console.warn("Validation Failed: Stage completion summary too short.");
            return false;
        }

        return true;
    }
};
